# Generated by Django 5.1.4 on 2024-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_pessoa_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ra', models.CharField(max_length=7, unique=True)),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('nota3', models.FloatField()),
                ('nota4', models.FloatField()),
                ('media', models.FloatField(editable=False)),
                ('status', models.CharField(editable=False, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
